version: "3.9"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853
      - 8081:8081
      - 8443:8443
    networks:
      - traefik
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
    volumes:
      - ${DOCKER_DIR_PREFIX}/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ${DOCKER_DIR_PREFIX}/pihole/pihole:/etc/pihole:rw
      - ${DOCKER_DIR_PREFIX}/pihole/lighttpd:/etc/lighttpd
    environment:
      WEBPASSWORD: ${PH_WEB_PASSWORD}
      WEB_BIND_ADDR: ${PH_WEB_ADDRESS}
      ServerIP: ${PH_WEB_ADDRESS}
      TZ: ${TZ}
      DNSMASQ_USER: ${PH_DNSMASQ_USER}
      DNSMASQ_LISTENING: ${PH_DNSMASQ_LISTENING}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.lan`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.services.pihole.loadbalancer.server.port=8443
      - traefik.http.routers.pihole.service=pihole
      - traefik.http.routers.pihole.middlewares=pihole-admin
      - traefik.http.middlewares.pihole-admin.addprefix.prefix=/admin
      - traefik.http.routers.pihole.tls=true

      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.pihole-http.rule=Host(`pihole.lan`)
      - traefik.http.routers.pihole-http.entrypoints=web
      - traefik.http.routers.pihole-http.middlewares=redirect-to-https

networks:
  traefik:
    external: true