services:
    portainer-ce:
        image: portainer/portainer-ce
        container_name: portainer
        ports:
            - 8000:8000
            - 9000:9000
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume1/docker/portainer:/data
        networks:
            - traefik
        labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.lan`)
      - traefik.http.routers.portainer-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.portainer-secure.service=portainer-service
      - traefik.http.services.portainer-service.loadbalancer.server.port=8096
      # Apply autentificiation with http challenge
      - traefik.http.routers.portainer-secure.tls.certresolver=lets-encr
      # Get the routes from http
      - traefik.http.routers.portainer.rule=Host(`portainer.lan`)
      - traefik.http.routers.portainer.entrypoints=web
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.portainer.middlewares=redirect-to-https@docker

networks:
  traefik:
    external: true
        