version: "3.9"
services:
  chevereto:
    image: chevereto/chevereto:latest
    container_name: chevereto
    hostname: chevereto
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 4573:80
    networks:
      - traefik
      - backend
    volumes:
      - ${DOCKER_DIR_PREFIX}/chevereto/storage:/var/www/html/images/:rw
    environment:
      TZ: ${TZ}
      CHEVERETO_DB_HOST: chevereto-db
      CHEVERETO_DB_USER: ${CHEVERETO_DB_USER}
      CHEVERETO_DB_PASS: ${CHEVERETO_DB_PASS}
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: ${CHEVERETO_DB_NAME}
      CHEVERETO_HOSTNAME: photos.dem2s.com
      CHEVERETO_SERVICING: server
      CHEVERETO_HOSTNAME_PATH: /
      CHEVERETO_HTTPS: 1
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: http://photos.dem2s.com/images/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/images/_assets/
      CHEVERETO_MAX_EXECUTION_TIME_SECONDS: 60
      CHEVERETO_MAX_UPLOAD_SIZE: 40960M
      CHEVERETO_MAX_POST_SIZE: 40960M
      CHEVERETO_HEADER_CLIENT_IP: X-Real-IP
      CHEVERETO_LICENSE_KEY: ${CHEVERETO_LICENSE_KEY}
    restart: on-failure:5
    depends_on:
      db:
        condition: service_started
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from http
      - traefik.http.routers.photos-dem2s.rule=Host(`photos.dem2s.com`)
      - traefik.http.routers.photos-dem2s.entrypoints=web
      # Define service and service load balancer
      - traefik.http.services.photos-dem2s.loadbalancer.server.port=80
      - traefik.http.routers.photos-dem2s.service=photos-dem2s
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.photos-dem2s.middlewares=redirect-to-https@docker
      # Get the routes from https
      - traefik.http.routers.photos-dem2s-secured.rule=Host(`photos.dem2s.com`)
      - traefik.http.routers.photos-dem2s-secured.entrypoints=websecure
      # Apply autentificiation with http challenge
      - traefik.http.routers.photos-dem2s-secured.tls=true
      - traefik.http.routers.photos-dem2s-secured.tls.certresolver=lets-encr
      # Implement crowdsec bouncer for traefik
      - traefik.http.routers.photos-dem2s-secured.middlewares=crowdsec@file
      
  db:
    image: mariadb:11.3-jammy
    container_name: chevereto-db
    hostname: chevereto-db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    user: 1026:100
    volumes:
      - ${DOCKER_DIR_PREFIX}/chevereto/db:/var/lib/mysql:rw
      - ${DOCKER_DIR_PREFIX}/chevereto/db:/etc/mysql/conf.d:rw
    environment:
      TZ: ${TZ}
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_DATABASE: ${CHEVERETO_DB_NAME}
      MARIADB_USER: ${CHEVERETO_DB_USER}
      MARIADB_PASSWORD: ${CHEVERETO_DB_PASS}
      MARIADB_MYSQL_LOCALHOST_GRANTS: SUPER
    restart: on-failure:5

networks:
  traefik:
    external: true
  backend:
    ipam:
      config:
        - subnet: 172.33.0.0/16
