services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from http
      - traefik.http.routers.whoami.rule=Host(`whoami.dem2s.com`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.service=whoami
      # Redirect these routes to https
      - traefik.http.routers.whoami.middlewares=redirect-to-https@file
      # Get the routes from https
      - traefik.http.routers.whoami-secure.rule=Host(`whoami.dem2s.com`)
      - traefik.http.routers.whoami-secure.entrypoints=websecure
      # Apply autentificiation with http challenge
      - traefik.http.routers.whoami-secure.tls.certresolver=lets-encr
      # CORS
      - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*
      - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*
      - traefik.http.middlewares.cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.cors.headers.addvaryheader=true
      - traefik.http.middlewares.cors.headers.customresponseheaders.Access-Control-Allow-Origin=*
      - traefik.http.routers.whoami-secure.middlewares=cors@docker
    networks:
      - traefik

networks:
  traefik:
    external: true