services:
  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from http
      - traefik.http.routers.whoami.rule=Host(`whoami.dem2s.com`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami.service=whoami
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.whoami.middlewares=redirect-to-https@docker
      # Get the routes from https
      - traefik.http.routers.whoami-secured.rule=Host(`whoami.dem2s.com`)
      - traefik.http.routers.whoami-secured.entrypoints=websecure
      # Apply autentificiation with http challenge
      - traefik.http.routers.whoami-secured.tls=true
      - traefik.http.routers.whoami-secured.tls.certresolver=lets-encr
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=${CS_LAPI_KEY}
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapischeme=http
      - traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapihost=crowdsec:8080
    networks:
      - traefik

networks:
  traefik:
    external: true