services:
  traefik:
    image: traefik:v3.5.0
    container_name: traefik
    volumes:
      - /volume1/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/traefik/acme.json:/acme.json
    networks:
      - traefik
    ports:
      - 880:80
      - 4443:443
      - 8080:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`traefik.lan`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=myresolver
    restart: unless-stopped

networks:
  traefik:
    external: true