services:
  traefik:
    image: traefik:v3.5.0
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yaml
    volumes:
      - /volume1/docker/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.api-secure.rule=Host(`traefik.lan`)
      - traefik.http.routers.api-secure.entrypoints=websecure
      - traefik.http.routers.api-secure.service=api@internal
      # Apply autentificiation with http challenge
      - traefik.http.routers.api-secure.tls.certresolver=lets-encr
      # Get the routes from https
      - traefik.http.routers.api.rule=Host(`traefik.lan`)
      - traefik.http.routers.api.entrypoints=web
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.api.middlewares=redirect-to-https@docker
    restart: unless-stopped

networks:
  traefik:
    external: true