# Entry points are the ports that Traefik listens on
entryPoints:
  web:
    address: :80 # HTTP port
  websecure:
    address: :443 # HTTPS port
  metrics:
    address: :8899

# certificatesResolvers are used to generate SSL certificates
certificatesResolvers: # Certificate resolver
  lets-encr:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
      email: cjhetz@gmail.com
      httpChallenge:
        entryPoint: web
        delay: 15

# This enables the webinterface and API for Traefik
api: # Web interface enable
  dashboard: true
  insecure: true
  
#http:
#  middlewares:
#    websocket-headers:
#      headers:
#        customRequestHeaders:
#          Connection: "Upgrade"
#          Upgrade: "websocket"

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true


accessLog:
  format: json
  filePath: /etc/traefik/logs/access.log

log:
  filePath: /etc/traefik/logs/traefik.log

# Providers are used to configure the dynamic configuration of Traefik
providers: # Providers
  docker: # Docker provider for dynamic configuration inside docker compose files
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file: # File provider for static
    filename: /etc/traefik/traefik.yaml
    watch: true