version: '3.9'
services:
  wordpress:
    image: wordpress:php8.2
    container_name: wordpress-dem2s
    restart: always
    networks:
      - traefik
      - backend
    ports:
      - 8182:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DEM2S_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DEM2S_WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DEM2S_WORDPRESS_DB_NAME}
    volumes:
      - ${DOCKER_DIR_PREFIX}/dem2s/wordpress:/var/www/html
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.wp-dem2s-secure.rule=Host(`dem2s.com`)
      - traefik.http.routers.wp-dem2s-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.wp-dem2s-secure.service=wp-dem2s-service
      - traefik.http.services.wp-dem2s-service.loadbalancer.server.port=80
      # Apply autentificiation with http challenge
      - traefik.http.routers.wp-dem2s-secure.tls.certresolver=lets-encr
      # Get the routes from http
      - traefik.http.routers.wp-dem2s.rule=Host(`dem2s.com`)
      - traefik.http.routers.wp-dem2s.entrypoints=web
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.wp-dem2s.middlewares=redirect-to-https@docker

  db:
    image: mysql
    container_name: wordpress-db-dem2s
    restart: always
    environment:
      MYSQL_DATABASE: ${DEM2S_WORDPRESS_DB_NAME}
      MYSQL_USER: ${DEM2S_WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${DEM2S_WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - backend
    volumes:
      - ${DOCKER_DIR_PREFIX}/dem2s/wordpressdb:/var/lib/mysql

networks:
  traefik:
    external: true
  backend: