services:
  cyber-chef:
    container_name: cyberchef
    healthcheck:
     test: curl -f http://localhost:8000/ || exit 1
    image: mpepping/cyberchef:latest
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 7318:8000
    networks:
      - traefik
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.cyberchef-secure.rule=Host(`cyberchef.local`) || Host(`cc.yakho.me`)
      - traefik.http.routers.cyberchef-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.cyberchef-secure.service=cyberchef-service
      - traefik.http.services.cyberchef-service.loadbalancer.server.port=8000
      # Apply autentificiation with http challenge
      - traefik.http.routers.cyberchef-secure.tls.certresolver=lets-encr
      - traefik.http.routers.cyberchef-secure.tls.domains[0].main=cc.yakho.me
      # Get the routes from http
      - traefik.http.routers.cyberchef.rule=Host(`cyberchef.local`) || Host(`cc.yakho.me`)
      - traefik.http.routers.cyberchef.entrypoints=web
      # Redirect these routes to https
      - traefik.http.routers.cyberchef.middlewares=redirect-to-https@file

networks:
  traefik:
    external: true
