services:
  cyber-chef:
    container_name: CyberChef
    healthcheck:
     test: curl -f http://localhost:8000/ || exit 1
    image: mpepping/cyberchef:latest
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 7318:8000
    networks:
      - traefik
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.dashy-secure.rule=Host(`home.lan`) || Host(`yakho.me`)
      - traefik.http.routers.dashy-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.dashy-secure.service=dashy-service
      - traefik.http.services.dashy-service.loadbalancer.server.port=8080
      # Apply autentificiation with http challenge
      - traefik.http.routers.dashy-secure.tls.certresolver=lets-encr
      # Get the routes from http
      - traefik.http.routers.dashy.rule=Host(`home.lan`) || Host(`yakho.me`)
      - traefik.http.routers.dashy.entrypoints=web
      # Redirect these routes to https
      - traefik.http.routers.dashy.middlewares=redirect-to-https@file

networks:
  traefik:
    external: true