services:
  projectsend:
    container_name: projectsend
    image: ghcr.io/linuxserver/projectsend
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    environment:
      MAX_UPLOAD: 20000
      MYSQL_DATABASE: ${PS_MYSQL_DB_NAME}
      MYSQL_USER: ${PS_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${PS_MYSQL_DB_PASSWORD}
      PUID: 1026
      PGID: 100
      TZ: ${TZ}
    volumes:
      - ${DOCKER_DIR_PREFIX}/projectsend/config:/config:rw
      - ${DOCKER_DIR_PREFIX}/projectsend/data:/data:rw
    ports:
      - 8516:80
    networks:
      - backend
      - traefik
    depends_on:
      db:
        condition: service_started
    restart: on-failure:5
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.dl-cjhphotos-secure.rule=Host(`downloads.cjh.photos`)
      - traefik.http.routers.dl-cjhphotos-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.dl-cjhphotos-secure.service=dl-cjhphotos-service
      - traefik.http.services.dl-cjhphotos-service.loadbalancer.server.port=80
      # Apply autentificiation with http challenge
      - traefik.http.routers.dl-cjhphotos-secure.tls.certresolver=lets-encr
      # Get the routes from http
      - traefik.http.routers.dl-cjhphotos.rule=Host(`downloads.cjh.photos`)
      - traefik.http.routers.dl-cjhphotos.entrypoints=web
      # Redirect these routes to https
      - traefik.http.routers.dl-cjhphotos.middlewares=redirect-to-https@file
    
  db:
    container_name: projectsend-db
    image: mariadb:11.4-noble #LTS Long Time Support Until May 29, 2029.
    security_opt:
      - no-new-privileges:false
    environment:
      MYSQL_ROOT_PASSWORD: ${PS_MYSQL_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PS_MYSQL_DB_NAME}
      MYSQL_USER: ${PS_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${PS_MYSQL_DB_PASSWORD}
      TZ: ${TZ}
    networks:
      - backend
    volumes:
      - ${DOCKER_DIR_PREFIX}/projectsend/db:/var/lib/mysql:rw
    restart: on-failure:5

networks:
  backend:
  traefik:
    external: true