services:
  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:v1.7.0-rc4 ## container labels were introduced in 1.6.2
    restart: always
    networks:
      - crowdsec-net
      - prometheus-net
      - traefik
    environment:
      - 'DOCKER_HOST: tcp://socket-proxy:2375'
      ## Please note the spaces between the collections names (hence why the quotes are needed)
      - 'COLLECTIONS=crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/traefik'
    ports:
      - 8083:8080
    depends_on:
      - 'socket-proxy'
    volumes:
      - ${DOCKER_DIR_PREFIX}/crowdsec/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
      - ${DOCKER_DIR_PREFIX}/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    labels:
      # The labels are usefull for Traefik only
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Get the routes from https
      - traefik.http.routers.crowdsec-secure.rule=Host(`crowdsec.lan`)
      - traefik.http.routers.crowdsec-secure.entrypoints=websecure
      # Specify the service name and the service loadbalancer port
      - traefik.http.routers.crowdsec-secure.service=crowdsec-service
      - traefik.http.services.crowdsec-service.loadbalancer.server.port=8080
      # Apply autentificiation with http challenge
      - traefik.http.routers.crowdsec-secure.tls.certresolver=lets-encr
      # Get the routes from http
      - traefik.http.routers.crowdsec.rule=Host(`crowdsec.lan`)
      - traefik.http.routers.crowdsec.entrypoints=web
      # Redirect these routes to https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.crowdsec.middlewares=redirect-to-https@docker

  socket-proxy:
    networks:
      - crowdsec-net
      - traefik
    restart: always
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    environment:
      - ALLOW_START=0 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=0 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=0 #optional
      - INFO=1 #optional
      - LOG_LEVEL=info #optional
      - NETWORKS=0 #optional
      - NODES=0 #optional
      - PING=1 #optional
      - PLUGINS=0 #optional
      - POST=0 #optional
      - SECRETS=0 #optional
      - SERVICES=0 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=0 #optional
      - VERSION=1 #optional
      - VOLUMES=0 #optional
    volumes:
      - '${DOCKER_DIR_SOCK}:/var/run/docker.sock:ro'
    read_only: true
    tmpfs:
      - /run

volumes:
  crowdsec-db:
  crowdsec-config:

networks:
  crowdsec-net:
    driver: bridge
  prometheus-net:
    external: true
  traefik:
    external: true